services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=Soumo'
      - 'POSTGRES_PASSWORD=Soum@deep28'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5431:5432'